import { CarData } from "../landing/type";

export const CARS_DATA: CarData[] = [
  {
    id: 6,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-BYD-TANG-L-EV-HESUCAR-2(1).png",
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-tang-l-ev-auto-in-china-1(1).webp",
    ],
    name: "Tang L Light Green",
    brand: "Byd",
    category: "Tang",
    price: 7200000,
    quantity: 3,
    isNew: false,
    description:
      "A large, premium plug-in hybrid SUV known for its three-row seating and luxurious interior. The light green finish adds a fresh, unique touch to its commanding road presence.",
    yearOfMfg: 2025,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 7,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-tang-l-ev-auto-in-china-1(1).webp",
    ],
    name: "Tang L Gray",
    brand: "Byd",
    category: "Tang",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "This spacious plug-in hybrid SUV offers impressive power and long-range",
    yearOfMfg: 2025,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 8,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-volkswagen-id.6-specs-21(1).png",
    ],
    name: "ID 6 Shampine",
    brand: "Byd",
    category: "ID",
    price: 7200000,
    quantity: 4,
    isNew: false,
    description:
      "A three-row electric SUV from Volkswagen designed specifically for families who need extra space and comfort. The champagne color emphasizes its upscale and elegant design.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 9,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-IMG_0222(1).png",
    ],
    name: "AWD bz4x Gray",
    brand: "Toyota",
    category: "BZ",
    price: 7200000,
    quantity: 4,
    isNew: false,
    description:
      "Toyota's modern electric SUV featuring All-Wheel Drive for enhanced traction and performance. Its sharp, futuristic lines look particularly sophisticated in gray.",
    yearOfMfg: 2023,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 10,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-Cover_(10)(1).png",
    ],
    name: "Leopard Crame",
    brand: "Byd",
    category: "Leopard",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A rugged, boxy off-road SUV (often known as the Fang Cheng Bao 5) that mixes hardcore 4x4 capability with hybrid technology. The cream color highlights its retro-modern, adventurous styling.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 11,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-Cover_(1).png",
    ],
    name: "Sealion 05 Shadow Gray",
    brand: "Byd",
    category: "Sealion",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      'A stylish mid-size plug-in hybrid SUV that is part of BYD\'s "Ocean" series, offering great fuel efficiency. The shadow gray paint enhances its sporty and dynamic body lines',
    yearOfMfg: 2025,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 12,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385439-sealion6-phev-hybrid-dmtechnology-performance-eco-fuel-power-battery-1080px-810px(1).png",
    ],
    name: "Seagull Crame",
    brand: "Byd",
    category: "Seagull",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A compact, affordable electric hatchback that is perfect for navigating tight city streets and parking easily. The cream finish gives this small city car a warm and trendy appearance.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 13,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385438-BYD-Song-L-MIIT(1).png",
    ],
    name: "Song Plus Smoking",
    brand: "Byd",
    category: "Song",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      'A best-selling mid-size SUV known for its excellent balance of technology, comfort, and fuel economy. The "smoking" grey color adds a stealthy and premium feel to the exterior.',
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 14,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385437-FuDuiAuto_HOZON-NETA-X-2024_002(1).jpg",
    ],
    name: "Song Plus Black",
    brand: "Byd",
    category: "Song",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "This popular SUV offers a smooth ride and a spacious cabin, making it a reliable choice for daily commuting. In black, it offers a classic, executive look that never goes out of style.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 16,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385438-byd-yuan-up-auto-in-china-1(1).png",
    ],
    name: "Yuan up White",
    brand: "Byd",
    category: "Yuan",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A compact electric SUV designed for urban living with a rugged yet youthful look. The white exterior makes the car look crisp, clean, and larger than it actually is.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 17,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385438-FuDuiAuto_BYD-Yuan-UP-2024_002(1).png",
    ],
    name: "Yuan up Light green",
    brand: "Byd",
    category: "Yuan",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "This entry-level electric SUV offers great tech features and agility in a small package. The light green color reflects its eco-friendly nature and fun personality.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 18,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385438-byd-yuan-up2024-side(1).jpg",
    ],
    name: "Yuan Plus Gray",
    brand: "Byd",
    category: "Yuan",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A sporty and aerodynamic electric SUV (known globally as the Atto 3) with a distinctive, fitness-themed interior. The gray finish makes it look modern and high-tech.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
  {
    id: 19,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385438-maxresdefault(1).jpg",
    ],
    name: "Leopard Blue",
    brand: "Byd",
    category: "Leopard",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A powerful off-road hybrid SUV built to handle tough terrain while keeping passengers comfortable. The blue exterior underlines its adventurous spirit and stands out on the road.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "Plug-in Hybrid",
  },
  {
    id: 20,
    images: [
      "https://jcarmall.r2.orpad.cc/jcarmall/uploads/products/1765398385437-FuDuiAuto_HOZON-NETA-X-2024_002(1).jpg",
    ],
    name: "Neta X Black",
    brand: "Neta",
    category: "Neta",
    price: 7200000,
    quantity: 5,
    isNew: false,
    description:
      "A value-focused electric SUV that prioritizes cabin space and smart technology. The black exterior gives this affordable EV a sleek and sophisticated profile.",
    yearOfMfg: 2024,
    mileage: 19288,
    fuel: "EV",
  },
];
